version: '3'
services:
  flask_app1:
    build: 
      context: ./flask_app1
      dockerfile: Dockerfile-pyapp1
    ports:
      - "8001:8000"
  nginx:
    build: 
      context: ./nginx_alb
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - flask_app1

